title: incyi's homepage
description: Some projects

github: [metadata]
 encoding: UTF-8
 kramdown:
   input: GFM
   hard_wrap: false
 future: true
 jailed: false
 theme: jekyll-theme-architect
 gfm_quirks: paragraph_end
 
google_analytics: [UA-108374030-1]
url: 'https://incyi.github.io'
twitter_username: incyi
github_username: incyi

plugins:
 - jekyll-feed
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-avatar
 - jemoji
 - jekyll-mentions
 - jekyll-include-cache