title: incyi's homepage
description: Some personal projects
theme: jekyll-theme-architect
google_analytics: [UA-108374030-1]
url: 'https://incyi.github.io'
github_username: incyi
github: [metadata]
show_downloads: false
plugins:
  - jekyll-sitemap
